### ISSUE TITLE
Godot 3.5 support

### ISSUE THREAD

**Issue by SanderVanhove** [samuelbigos/godot_2d_navmesh_generator#1]
There are multiple errors preventing this plugin to work on anything other than Godot 3.2. I would love to port this plugin to 3.5 but run into some errors I can't start to solve because the implementation is fairly big. Is there some way to contact you directly and ask some questions about the structure of the plugin?

**Comment by samuelbigos** [comment]
Hey Sander. I am Calneon#3773 on Discord, that's probably the best way to get in touch.

**Comment by samuelbigos** [comment]
I just tried the demo project on the latest Godot version (v3.5.1), and it worked correctly for me. I did get an error when re-creating the NavigationPolygon, it seems checking for null in plugin.gd line 24 is no longer enough and is_instance_valid() must be used instead. But after making that change I can generate a new navmesh.
